# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_app', '0002_auto_20180108_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdings',
            name='currency',
            field=models.CharField(choices=[('EUR', '€'), ('USD', '$')], default='EUR', max_length=3),
        ),
    ]
