# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coin_app', '0005_auto_20180110_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdings',
            name='exchange',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coin_app.Exchange'),
        ),
        migrations.AlterField(
            model_name='holdings',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=60),
        ),
        migrations.AlterUniqueTogether(
            name='holdings',
            unique_together=set([('coin_id', 'user', 'exchange')]),
        ),
    ]
