# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_app', '0003_holdings_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR (€)'), ('USD', 'USD($)')], default='EUR', max_length=3),
        ),
    ]
