# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin_app', '0004_auto_20180110_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdings',
            name='currency',
        ),
        migrations.AlterField(
            model_name='holdings',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
